#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/lib.sh"

load_conda

export CARLA_HOST
export CARLA_PORT
export CARLA_CONNECT_TIMEOUT
export CARLA_DEPLOY_TIMEOUT
export CARLA_RUNTIME_TIMEOUT
export CARLA_API_PORT="${API_PORT}"
export MANUAL_BRIDGE_SCRIPT
export MANUAL_BRIDGE_STATUS_FILE
export CARLA_CAN_DBC
export CARLA_TCP_CAN_HOST
export CARLA_TCP_CAN_PORT
export CARLA_TCP_CAN_RECONNECT_SEC
export CARLA_CAN_REVERSE_GEARS
export CARLA_CAN_DRIVE_GEARS
export CENTER_DISPLAY_AUTO_START
export OFFICIAL_ENABLE_SENSORS
export OFFICIAL_SENSOR_UDP_PORTS
export OFFICIAL_SENSOR_SUMMARY_HZ
export OFFICIAL_SENSOR_UDP_HZ
export OFFICIAL_SENSOR_SAMPLE_LIMIT
export OFFICIAL_SENSOR_LIDAR_MAX_PPS
export OFFICIAL_SENSOR_LIDAR_MAX_HZ
export OFFICIAL_AIGO_DISABLE_SENSORS
export OFFICIAL_AIGO_DISABLE_SIDE_MIRRORS
export OFFICIAL_AI_BASELINE_DISABLE_SENSORS
export OFFICIAL_AI_BASELINE_DISABLE_SIDE_MIRRORS
export OFFICIAL_SIDE_MIRRORS_ALWAYS_ON
export OFFICIAL_AI_USE_MAP_SPAWN
export OFFICIAL_AI_IGNORE_LIGHTS_PERCENT
export OFFICIAL_AI_IGNORE_SIGNS_PERCENT
export OFFICIAL_TRAFFIC_MANAGER_PORT
export OFFICIAL_FIXED_DELTA_SECONDS
export OFFICIAL_MAX_SUBSTEP_DELTA_TIME
export OFFICIAL_MAX_SUBSTEPS
export OFFICIAL_CAMERA_SENSOR_TICK
export OFFICIAL_DISPLAY_LOOP_HZ

cd "${PROJECT_DIR}"

BACKEND_SCRIPT="${CARLA_BACKEND_SCRIPT:-official_carla_demo/official_demo_gateway.py}"
if [ ! -f "${PROJECT_DIR}/${BACKEND_SCRIPT}" ]; then
  log "ERROR: backend script not found: ${PROJECT_DIR}/${BACKEND_SCRIPT}"
  exit 2
fi

log "Waiting for CARLA before backend startup"
python "${SCRIPT_DIR}/wait_for_carla.py" \
  --host "${CARLA_HOST}" \
  --port "${CARLA_PORT}" \
  --timeout 240 \
  --client-timeout 5

log "Starting backend-only ${BACKEND_SCRIPT} API ${API_PORT}"
exec python "${PROJECT_DIR}/${BACKEND_SCRIPT}"
