#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${CARLA_PROJECT_ROOT:-${HOME}/Carla_Project}"
RUNTIME_DIR="${PROJECT_DIR}/official_carla_demo/runtime"

if [ ! -f "${RUNTIME_DIR}/lib.sh" ]; then
  echo "ERROR: missing ${RUNTIME_DIR}/lib.sh"
  exit 2
fi

# shellcheck source=/dev/null
source "${RUNTIME_DIR}/lib.sh"

if ! wait_for_display "${DISPLAY_WAIT_SEC:-120}"; then
  log "ERROR: no graphical X11 display is ready"
  exit 3
fi
resolve_xauthority

export CARLA_PROJECT_ROOT="${PROJECT_DIR}"
export CARLA_BACKEND_SCRIPT="official_carla_demo/official_demo_gateway.py"
export CENTER_DISPLAY_AUTO_START=0
export OFFICIAL_DEMO_RES="${OFFICIAL_DEMO_RES:-1920x1080}"
export OFFICIAL_DEMO_FULLSCREEN="${OFFICIAL_DEMO_FULLSCREEN:-1}"
export OFFICIAL_COMMAND_COOLDOWN_SEC="${OFFICIAL_COMMAND_COOLDOWN_SEC:-25}"
export OFFICIAL_TERMINATE_TIMEOUT_SEC="${OFFICIAL_TERMINATE_TIMEOUT_SEC:-20}"
export OFFICIAL_RELAUNCH_GAP_SEC="${OFFICIAL_RELAUNCH_GAP_SEC:-4.0}"
export OFFICIAL_CARLA_CLIENT_TIMEOUT="${OFFICIAL_CARLA_CLIENT_TIMEOUT:-60}"
export OFFICIAL_FIXED_DELTA_SECONDS="${OFFICIAL_FIXED_DELTA_SECONDS:-0.02}"
export OFFICIAL_MAX_SUBSTEP_DELTA_TIME="${OFFICIAL_MAX_SUBSTEP_DELTA_TIME:-0.005}"
export OFFICIAL_MAX_SUBSTEPS="${OFFICIAL_MAX_SUBSTEPS:-16}"
export OFFICIAL_TRAFFIC_MANAGER_PORT="${OFFICIAL_TRAFFIC_MANAGER_PORT:-8000}"
export OFFICIAL_CAMERA_SENSOR_TICK="${OFFICIAL_CAMERA_SENSOR_TICK:-0.02}"
export OFFICIAL_DISPLAY_LOOP_HZ="${OFFICIAL_DISPLAY_LOOP_HZ:-60}"
export OFFICIAL_DISABLE_SIDE_MIRRORS="${OFFICIAL_DISABLE_SIDE_MIRRORS:-1}"
export OFFICIAL_SIDE_RTSP_HOST="${OFFICIAL_SIDE_RTSP_HOST:-192.168.110.100}"
export OFFICIAL_SIDE_RTSP_PORT="${OFFICIAL_SIDE_RTSP_PORT:-8554}"
export OFFICIAL_REAR_LEFT_STREAM_URL="${OFFICIAL_REAR_LEFT_STREAM_URL:-rtsp://192.168.110.100:8554/carla_rear_left}"
export OFFICIAL_REAR_RIGHT_STREAM_URL="${OFFICIAL_REAR_RIGHT_STREAM_URL:-rtsp://192.168.110.100:8554/carla_rear_right}"
export OFFICIAL_BIRDVIEW_STREAM_URL="${OFFICIAL_BIRDVIEW_STREAM_URL:-rtsp://192.168.110.100:8554/carla_birdview}"
export OFFICIAL_AI_FALLBACK_ENABLED="${OFFICIAL_AI_FALLBACK_ENABLED:-0}"
export OFFICIAL_ROUTE_TM_SPEED_DIFFERENCE_PERCENT="${OFFICIAL_ROUTE_TM_SPEED_DIFFERENCE_PERCENT:-0}"
export OFFICIAL_ROUTE_ARRIVAL_DISTANCE_M="${OFFICIAL_ROUTE_ARRIVAL_DISTANCE_M:-2.0}"
export CARLA_EXAMPLES_DIR="${CARLA_EXAMPLES_DIR:-${HOME}/Workspace/carla_hil_project/PythonAPI/examples}"
export CARLA_PYTHONAPI="${CARLA_PYTHONAPI:-${HOME}/Workspace/carla_hil_project/PythonAPI/carla}"
export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-x11}"
export SDL_VIDEO_WINDOW_POS="${SDL_VIDEO_WINDOW_POS:-0,0}"

exec "${RUNTIME_DIR}/start_backend.sh"
